### ISSUE TITLE
Issue with adblock also blocking FrankerFaceZ

### ISSUE THREAD

**Issue by codlycod** [RMED24/twitch-ad-block#1]
Hello, it seems to work so far but it is blocking emote extension FrankerFaceZ from working even if it is enabled. I tried uninstalling and re-installing it but still didn't work. Looks like the text that was put into My rules ended up blocking the extension as well.

**Comment by RMED24** [comment]
I will take a look into this and repair the issue later. Once it is fixed, I will post a comment and close the issue. Cheers!

**Comment by RMED24** [comment]
This has been fixed now. To apply this change on your end, update the text on your uBO extension settings with the new text on this page: https://raw.githubusercontent.com/RMED24/twitch-ad-block/main/raw.txt
