### ISSUE TITLE
Worked for a little bit but ads started coming through again

### ISSUE THREAD

**Issue by johnwoods431** [RMED24/twitch-ad-block#3]
Worked for about an hour but then ads started coming through again. Tried deleting the turning ublock off and on and deleting My rules text and readding it but still didn't work.

**Comment by RMED24** [comment]
This is very strange. I know twitch has methods sometimes to bypass adblockers like this, but in my testing this always worked properly for me. I'll take another look and see if I can improve the situation a bit more.

Also can I ask what browser you're using? Most of the stuff was tested on firefox and there is a chance it could be browser related. If I'm aware of the browser used then I can more easily attempt to debug the issue

**Comment by RMED24** [comment]
Also I know this is strange, but can I know what operating system you're running as well. Some websites have a habit of loading different code depending on your OS used

**Comment by johnwoods431** [comment]
> Also I know this is strange, but can I know what operating system you're running as well. Some websites have a habit of loading different code depending on your OS used

Using Chrome Browser as well as macOS Operating System.

**Comment by RMED24** [comment]
> Using Chrome Browser as well as macOS Operating System.

This isn't a permanent solution and I will look more into the issue, but can I request you temporarily use Firefox and watch twitch on that browser like you normally would? I want to deduce if this is a chrome related issue as there has been little time spent into making sure chrome works properly.

There's no rush for you to test this on Firefox, but it would make things a lot easier

**Comment by johnwoods431** [comment]
> > Using Chrome Browser as well as macOS Operating System.
> 
> This isn't a permanent solution and I will look more into the issue, but can I request you temporarily use Firefox and watch twitch on that browser like you normally would? I want to deduce if this is a chrome related issue as there has been little time spent into making sure chrome works properly.
> 
> There's no rush for you to test this on Firefox, but it would make things a lot easier

Yeah I gotchu, I'll give it a test tonight and see how if it works for me on there. Also, Happy New Year

**Comment by RMED24** [comment]
Happy new year to you as well man

**Comment by johnwoods431** [comment]
Tried out Firefox to watch twitch with the added Myrules on uBlock and the same issue still happened on there. Worked for about half an hour and then ads popped up constantly. Not sure but maybe because of I'm on macOS Operating System?

**Comment by RMED24** [comment]
I doubt it is because of mac. I think they're using a fallback method if ads keep failing which is rather annoying. I'll try to brute force my way through this issue eventually and ask you to test again. It may be a week or two so you are free for a while. Thank you for making this issue and I'll leave it open until I figure it out 😅

**Comment by johnwoods431** [comment]
> I doubt it is because of mac. I think they're using a fallback method if ads keep failing which is rather annoying. I'll try to brute force my way through this issue eventually and ask you to test again. It may be a week or two so you are free for a while. Thank you for making this issue and I'll leave it open until I figure it out 😅

I think the problem could be the uBlock Origin extension. It might be that Twitch's ad block detecting system is recognizing uBlock maybe because I to put the text that you made for 'My rules' into a different AdBlocker called 'AdBlocker Ultimate' and put in into their custom rules to see if it would block twitch ads through that extension and it seems to working really well so far. Over the past 2 days that I've been trying it, I've gotten few pre-roll ads from specific streamers but other than that it is working smoothly. I'm gonna keep testing it throughout the week to see if it stays like this though. Hope this helps!

**Comment by RMED24** [comment]
This is actually very useful information. I'll take a look further into this and see what is what. Thanks!

**Comment by RMED24** [comment]
I'm going to update my system soon but I want you to try these new settings on ublock origin with any browser. Bare in mind stuff may break due to this and I may need to make some adjustments. But I've done some light testing now. Here it is:
clips.twitch.tv * 3p-frame block
clips.twitch.tv * 3p-script block
clips.twitch.tv twitch.map.fastly.net * noop
clips.twitch.tv twitchcdn.net * noop
www.twitch.tv * 3p block
www.twitch.tv * 3p-frame block
www.twitch.tv * 3p-script block
www.twitch.tv cloudfront.net * noop
www.twitch.tv frankerfacez.com * noop
www.twitch.tv jtvnw.net * noop
www.twitch.tv ttvnw.net * noop
www.twitch.tv twitch.map.fastly.net * noop
www.twitch.tv twitchcdn.net * noop

**Comment by RMED24** [comment]
Make sure you clear out the previous URLs you applied in ublock origin before applying these new URL rules btw. I've made some adjustments to these URLs directly which may cause issues if you just copy and merge like normal

**Comment by Guiguioh** [comment]
I stumble upon your filter list and decided to test this extended one. It seems to work really well but since i have a few twitch extensions i had to add a few more lines because of the 3p block.

**Comment by RMED24** [comment]
> I stumble upon your filter list and decided to test this extended one. It seems to work really well but since i have a few twitch extensions i had to add a few more lines because of the 3p block.

Ugh I should have figured that would cause issues. However removing that 3p block will cause ads to leak through again. I'll take another look and try to fix it. Cheers for letting me know

**Comment by RMED24** [comment]
Oh wait you've edited your message since I saw it in the email. Would you mind posting the filter list with the new filters that do work with 3p block and frankerfaceZ? I'll try and test that

**Comment by Guiguioh** [comment]
Sure 
clips.twitch.tv * 3p-frame block
clips.twitch.tv * 3p-script block
clips.twitch.tv twitch.map.fastly.net * noop
clips.twitch.tv twitchcdn.net * noop
www.twitch.tv * 3p block
www.twitch.tv * 3p-frame block
www.twitch.tv * 3p-script block
www.twitch.tv 7tv.app * noop
www.twitch.tv betterttv.net * noop
www.twitch.tv chatterino.com * noop
www.twitch.tv cloudfront.net * noop
www.twitch.tv echtkpvl.de * noop
www.twitch.tv ffzap.com * noop
www.twitch.tv fourtf.com * noop
www.twitch.tv frankerfacez.com * noop
www.twitch.tv ggpht.com * noop
www.twitch.tv github.com * noop
www.twitch.tv githubusercontent.com * noop
www.twitch.tv imgur.com * noop
www.twitch.tv jtvnw.net * noop
www.twitch.tv spore.build * noop
www.twitch.tv ttv.lol * noop
www.twitch.tv ttvnw.net * noop
www.twitch.tv twimg.com * noop
www.twitch.tv twitch.map.fastly.net * noop
www.twitch.tv twitchcdn.net * noop
www.twitch.tv twitter.com * noop
www.twitch.tv ytimg.com * noop

**Comment by RMED24** [comment]
I'll test this later and if this works properly then it'll be the new filter list. Thanks again!

**Comment by RMED24** [comment]
This was fixed in #4 thanks to @Guiguioh. I am sorry it took so long but glad to say it has been resolved
